apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: rag-postgres
    type: postgres
    access: proxy
    url: rag-postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
